name: Tag Release

on:
  push:
    branches:
      - main

jobs:
  tag_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Read version from file
        id: version
        run: echo "${{ github.event.client_payload.version }}" > version.txt

      - name: Create tag
        run: git tag ${{ steps.version.outputs.version }}

      - name: Push tag
        run: git push origin ${{ steps.version.outputs.version }}

